# Generated by Django 2.1.5 on 2019-01-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=20, max_digits=25)),
                ('high', models.DecimalField(decimal_places=20, max_digits=25)),
                ('low', models.DecimalField(decimal_places=20, max_digits=25)),
                ('volume', models.DecimalField(decimal_places=20, max_digits=25)),
                ('last', models.DecimalField(decimal_places=20, max_digits=25)),
                ('volume_30day', models.DecimalField(decimal_places=20, max_digits=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.Product')),
            ],
        ),
    ]
