# Generated by Django 2.1.5 on 2019-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatistics',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstatistics',
            name='last',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstatistics',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstatistics',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstatistics',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstatistics',
            name='volume_30day',
            field=models.FloatField(),
        ),
    ]
