# Generated by Django 2.1.5 on 2019-01-24 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_auto_20190124_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatistics',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
