# Generated by Django 2.1.5 on 2019-01-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_productstatistics_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='marketdata.Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quote_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_currency', to='marketdata.Currency'),
        ),
    ]
